"""PDF export for meeting notes."""

from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from meeting_assistant.database import Meeting


class MeetingExporter:
    """Export meeting notes to PDF format."""

    EXPORTS_DIR = Path("exports")

    def __init__(self, exports_dir: str | Path | None = None):
        self.exports_dir = Path(
            exports_dir) if exports_dir else self.EXPORTS_DIR
        self.exports_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _sanitize(text: str) -> str:
        """Replace common Unicode characters unsupported by Helvetica."""
        replacements = {
            "\u2022": "-",    # bullet
            "\u2013": "-",    # en dash
            "\u2014": "-",    # em dash
            "\u2018": "'",    # left single quote
            "\u2019": "'",    # right single quote
            "\u201c": '"',    # left double quote
            "\u201d": '"',    # right double quote
            "\u2026": "...",  # ellipsis
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        return text

    def export_to_pdf(self, meeting: Meeting) -> Path:
        """
        Export a meeting to a formatted PDF file.

        Args:
            meeting: The Meeting object to export.

        Returns:
            Path to the generated PDF file.
        """
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 12, self._sanitize(meeting.title),
                 new_x="LMARGIN", new_y="NEXT")

        # Date
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 8, f"Date: {meeting.date}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)

        # Summary
        if meeting.summary:
            self._add_section(pdf, "Summary", meeting.summary)

        # Key Points
        if meeting.key_points:
            self._add_list_section(pdf, "Key Points", meeting.key_points)

        # Action Items
        if meeting.action_items:
            self._add_list_section(pdf, "Action Items", meeting.action_items)

        # Full Transcript
        if meeting.transcript:
            self._add_section(pdf, "Full Transcript", meeting.transcript)

        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(
            0, 5,
            f"Generated by Meeting Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            new_x="LMARGIN", new_y="NEXT",
        )

        # Save
        safe_title = "".join(
            c if c.isalnum() or c in " -_" else "" for c in meeting.title)
        filename = f"{safe_title}_{meeting.date[:10]}.pdf"
        output_path = self.exports_dir / filename
        pdf.output(str(output_path))
        return output_path

    def _add_section(self, pdf: FPDF, title: str, content: str) -> None:
        """Add a titled text section to the PDF."""
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, self._sanitize(content))
        pdf.ln(5)

    def _add_list_section(self, pdf: FPDF, title: str, items: list[str]) -> None:
        """Add a titled bullet-point list section to the PDF."""
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for item in items:
            pdf.cell(5)  # indent
            pdf.multi_cell(0, 6, f"-  {self._sanitize(item)}")
            pdf.ln(1)
        pdf.ln(3)
